public class JobApplicationRequest {
    public String FirstName{get;set;}
    public String LastName{get;set;}
    public String Email{get;set;}
    public String MailingStreet{get;set;}
    public String MailingCity{get;set;}
    public String MailingState{get;set;}
    public String MailingCountry{get;set;} 
    public String MailingPostalCode{get;set;}
    public String MobilePhone{get;set;}
    public String JobPostingId{get;set;}
}